management:
  endpoint:
    health:
      show-details: always

server:
  port: ${PORT:8080}

mongo:
  connection-string: "mongodb+srv://king:6EQUJ5@medievalwarfare.nbkps.mongodb.net/game?w=majority"

firebase-cloud-messaging:
    type: "service_account"
    project-id: "medieval-warfare"
    client-email: "firebase-adminsdk-8hw2l@medieval-warfare.iam.gserviceaccount.com"
    client-id: "115671543833939047931"
    auth-uri: "https://accounts.google.com/o/oauth2/auth"
    token-uri: "https://oauth2.googleapis.com/token"
    auth-provider-x509-cert-url: "https://www.googleapis.com/oauth2/v1/certs"
    client-x509-cert-url: "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-8hw2l%40medieval-warfare.iam.gserviceaccount.com"
    private-key-id: ${APP_PRIVATE_KEY_ID}
    private-key:  ${APP_PRIVATE_KEY}


security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

logging:
  level:
    com.ynov.master.mobile.game.medieval.warfare: info

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by id
  me: Returns current user's data