name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Build > Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify