name: Continuous Integration

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Build > Checkout Code
        uses: actions/checkout@v2

